/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 scene.gltf 
Author: TopboyXO (https://sketchfab.com/TopboyXO)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/reality-scan-3d-male-character-36bbc857692b49bfa44a8bed7fbb847b
Title: Reality Scan 3D Male Character
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Male(props) {
  const { scene } = useGLTF('reality_scan_3d_male_character/scene.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null} scale={[3, 3, 3]} position={[0, -3, 0]}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]} scale={0.01}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh geometry={nodes.Object_6.geometry} material={materials.Std_Tongue} skeleton={nodes.Object_6.skeleton} />
          <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.Std_Skin_Head} skeleton={nodes.Object_8.skeleton} />
          <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.Std_Skin_Body} skeleton={nodes.Object_9.skeleton} />
          <skinnedMesh geometry={nodes.Object_10.geometry} material={materials.Std_Skin_Arm} skeleton={nodes.Object_10.skeleton} />
          <skinnedMesh geometry={nodes.Object_11.geometry} material={materials.Std_Skin_Leg} skeleton={nodes.Object_11.skeleton} />
          <skinnedMesh geometry={nodes.Object_12.geometry} material={materials.Std_Nails} skeleton={nodes.Object_12.skeleton} />
          <skinnedMesh geometry={nodes.Object_13.geometry} material={materials.Std_Eyelash} skeleton={nodes.Object_13.skeleton} />
          <skinnedMesh geometry={nodes.Object_15.geometry} material={materials.Std_Eye_R} skeleton={nodes.Object_15.skeleton} />
          <skinnedMesh geometry={nodes.Object_16.geometry} material={materials.Std_Cornea_R} skeleton={nodes.Object_16.skeleton} />
          <skinnedMesh geometry={nodes.Object_17.geometry} material={materials.Std_Eye_L} skeleton={nodes.Object_17.skeleton} />
          <skinnedMesh geometry={nodes.Object_18.geometry} material={materials.Std_Cornea_L} skeleton={nodes.Object_18.skeleton} />
          <skinnedMesh geometry={nodes.Object_20.geometry} material={materials.Std_Upper_Teeth} skeleton={nodes.Object_20.skeleton} />
          <skinnedMesh geometry={nodes.Object_21.geometry} material={materials.Std_Lower_Teeth} skeleton={nodes.Object_21.skeleton} />
          <skinnedMesh geometry={nodes.Object_23.geometry} material={materials.Std_Tearline_R} skeleton={nodes.Object_23.skeleton} />
          <skinnedMesh geometry={nodes.Object_24.geometry} material={materials.Std_Tearline_L} skeleton={nodes.Object_24.skeleton} />
          <skinnedMesh geometry={nodes.Object_26.geometry} material={materials.Std_Eye_Occlusion_R} skeleton={nodes.Object_26.skeleton} />
          <skinnedMesh geometry={nodes.Object_27.geometry} material={materials.Std_Eye_Occlusion_L} skeleton={nodes.Object_27.skeleton} />
          <skinnedMesh geometry={nodes.Object_29.geometry} material={materials.Boxers} skeleton={nodes.Object_29.skeleton} />
          <skinnedMesh geometry={nodes.Object_31.geometry} material={materials.Hair_Transparency} skeleton={nodes.Object_31.skeleton} />
          <skinnedMesh geometry={nodes.Object_32.geometry} material={materials.Scalp_Transparency} skeleton={nodes.Object_32.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('reality_scan_3d_male_character/scene.gltf')
