/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 scene.gltf 
Author: Shift4cube (https://sketchfab.com/Shift4cube)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tank-top-d6b2561de39f423f9c7a2e7944485beb
Title: Tank Top
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function TankTop(props) {
  const { nodes, materials } = useGLTF('tank_top/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.00336, 0.00361, 0.0034]} position={[0, -3.7, -0.04]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.FABRIC_3_FRONT_2680} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Stylized_Rib_Knit_Wool_Copy_1_FRONT_2685} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Stylized_Rib_Knit_Wool_FRONT_2656} />
      </group>
    </group>
  )
}

useGLTF.preload('tank_top/scene.gltf')
